# http://www.nfd.com.tw/lottery/49-year/49-2004.htm
# http://www.nfd.com.tw/lottery/power-38/2008.htm
# http://www.nfd.com.tw/lottery/39-year/39-2007.htm
# http://www.nfd.com.tw/lottery/4-star/2003.htm
http:
  base: "http://www.nfd.com.tw/lottery"
  infos: 
    - label: "39-%d.htm"
      path: "39-year"
      baseyear: "2007"
    - label: "49-%d.htm"
      path: "49-year"
      baseyear: "2004"
    - label: "%d.htm"
      path: "power-38"
      baseyear: "2008"
    - label: "%d.htm"
      path: "4-star"
      baseyear: "2003"
local:
    path: ../../data/csv

aokurls:
  - url: "http://www.aok.url.tw/yomj/114/114%E5%B9%B4%E5%BA%A6%E5%A4%A7%E6%A8%82%E9%80%8F%E9%96%8B%E7%8D%8E%E8%99%9F%E7%A2%BC%E8%A1%A8.doc"
    local_path: ./data/doc/bl
  - url: "http://www.aok.url.tw/yomj/114/114%E5%B9%B4%E5%BA%A6%E4%BB%8A%E5%BD%A9539%E9%96%8B%E7%8D%8E%E8%99%9F%E7%A2%BC%E8%A1%A8.doc"
    local_path: ./data/doc/ftn
  - url: "http://www.aok.url.tw/yomj/114/114%E5%B9%B4%E5%BA%A6%E5%A8%81%E5%8A%9B%E5%BD%A9%E9%96%8B%E7%8D%8E%E8%99%9F%E7%A2%BC%E8%A1%A8.doc"
    local_path: ./data/doc/pow
  - url: "http://www.aok.url.tw/yomj/114/114%E5%B9%B4%E5%BA%A63%E3%80%814%E6%98%9F%E5%BD%A9%E9%96%8B%E7%8D%8E%E8%A1%A8.doc"
    local_path: ./data/doc/star34

combinations:
  - path: ../../data/statics
    template: "combination%v.json"
    
